### ISSUE TITLE
call_name() now unwraps `::` calls

### ISSUE THREAD

**Issue by lionel-** [mailund/pmatch#50] opened 2018-12-13 14:04 UTC
Hi Thomas,

In the next patch release of rlang, `call_name(quote(foo::bar))` is an error because the input is now implicitly unwrapped from the `::` call. See https://github.com/r-lib/rlang/issues/670 for more context. I'd like to send a release to CRAN in a couple of weeks. Would it be possible to update pmatch in that timeframe?

Unrelatedly, I see you're using `quo_name()` to transform quosured symbols to strings. We're going to rename this function in the next major release because its name is misleading. It shouldn't be used for deterministic transformation such as string <-> symbol. It should only be used for default names, i.e. to create pretty labels. Perhaps the new name will be `label()`.

More generally, I think quosured symbols are often indicative of a design issue. If you have a quosure, you shouldn't assume (or be in a position to assume) the type of expression inside it (at least that is my current thinking).

**Comment by mailund** [comment] 2018-12-15 10:56
This might be a case of the GitHub version being ahead of the released version (and I am getting ready to submit a new release that is compatible with rlang 0.3.0), but I cannot find where I call call_name with a qualified name. It might also be a case of UQ() instead of !!, because I have just changed that. I do not get any errors or warnings when I run a check. I will commit my current version; could you check if the issue is still there?


As for the quo_name, I agree in general, but I use it for a special case. I only use it for type declarations which should be on the form

```r
typename := CONSTRUCTORS
```

so I should have a name and it is an error if it is not. I do check if it is a symbol and raise an error if it is not. I think that should be okay, but if you think there is a better solution I will love to hear it and fix the code.

**Comment by mailund** [comment] 2018-12-15 10:58
I actually had a similar issue in `foolbox` that was resolved by changing UQ to !!, so it could very well be that.

**Comment by lionel-** [comment] 2018-12-17 09:39
> This might be a case of the GitHub version being ahead of the released version

Could you try with the dev version please? `remotes::install_github("r-lib/rlang")`

> if you think there is a better solution I will love to hear it and fix the code.

Currently `as_string(quo_get_expr(quo))`, but I'm considering unwrapping quosures automatically in `as_string()` to provide an easy alternative to `quo_name()` with quosured symbols. That might well be the path of least resistance, even though I'm not a fan of silent lossy casts.

**Comment by mailund** [comment] 2018-12-17 12:39
That certainly broke it.

I have fixed that issue (but not committed it yet--I need a few more changes to remove warnings).

There are a few issues that concern me, though. I used the `foo::bar` calls to avoid namespace issues, and those do not go away just because I remove them in `pmatch`. If someone uses them qualified names when *calling* one of the functions in this package they will also run into the problem. Is there a way to get qualified names out of a call some other way?

I could imagine that I capture call names some other way, but are there any support for it in the new `rlang` or some idiomatic way to do this?

I'll fix the `quo_name` issue after I have removed the other warnings.

Cheers

**Comment by mailund** [comment] 2018-12-17 13:57
The main issues should be fixed, but I still have a problem with

```
Passing an environment as data mask is deprecated.
Please use `new_data_mask()` to transform your environment to a mask.

  env <- env(foo = "bar")

  # Bad:
  as_data_mask(env)
  eval_tidy(expr, env)

  # Good:
  mask <- new_data_mask(env)
  eval_tidy(expr, mask)
```

I haven't figured out how to deal with that yet. I need to mask one environment with another, but this only works for me in some cases and not others...

**Comment by lionel-** [comment] 2018-12-17 14:31
I updated the `?new_data_mask` documentation in 0.3.0, let me know if it's clearer. You likely need a multi-level mask, which you can easily accomplish by passing the bottom and the top of your environment chain.

I'm not sure I understand the issue with `call_name()`. It now expects a call, and `foo::bar` is no longer considered a call. I.e. it no longer supports namespaced symbols, only namespaced calls.

**Comment by mailund** [comment] 2018-12-17 14:39
I got rid of the function where I had `new_data_mask`. It is indeed a multi-level mask and I couldn't really figure out how to fix it in the time I have today, and in any case, it is in a function, `cases`, that I wanted to depreciate in any case. There is a faster replacement, `case_func`, so it is no major problem.

The `cases` function is also the only place where I needed qualified names (I think), so that should be okay as well.

Let me know if the latest commit works for you.

Cheers

**Comment by mailund** [comment] 2018-12-19 15:30
I've updated documentation and such and think I'm ready for submitting an updated version to CRAN, but please let me know if it now works on your end.

Cheers

**Comment by mailund** [comment] 2018-12-20 09:58
I'm declaring this issue resolved and will make a release compatible with the new version of rlang.

**Closed as completed by mailund** 2018-12-20 09:58 UTC
Labels: bug, enhancement

**Comment by lionel-** [comment] 2018-12-20 12:51
Hi Thomas,

After looking at your code, I realised that the new semantics of `call_name()` need a bit more thinking because the following should never throw:

```r
if (is_call(x)) {
  call_name(x)
}
```

That would mean `is_call(quote(foo::bar))` should return `FALSE`, but we need to consider the implications of such a change. While `call_name()` can be considered a high level function, it's not clear that `is_call()` can. Consequently, I have reverted the `call_name()` change for this patch release to give us more time to figure this out: https://github.com/r-lib/rlang/commit/d450ebf1e416d7e3fbac53660494181a26cf8e42

I just checked your package with dev rlang and everything is fine. Thanks for your patience on this.

About `quo_name()`, `as_string()` now unwraps quosured symbols for convenience and I'll soon add a `label()` function to replace `quo_name()`. That said, `quo_name()` will not be soft-deprecated until the next release cycle (0.4.x).

**Comment by mailund** [comment] 2018-12-20 13:02
I am not that patient and there is no need to thank me :) If anything I am thankful for the help in fixing this.

Isn't `::` an inline function? Then `foo::bar` *is* a call, surely? True, `::` is not a function you will want to modify (any more than you would want to change `if` or `for`), but still...

I replaced the `quo_name()` code with the (last line of) the code below. 

```r
    if (!rlang::quo_is_symbol(data_type)) {
        error_msg <- glue::glue(
            "Incorrect type specification: {rlang::quo_expr(data_type)}. ",
            "The type must be a bare symbol."
        )
        stop(simpleError(error_msg, call = match.call()))
    }

    data_type_name <- rlang::as_string(rlang::quo_get_expr(data_type))
```

The left-hand side of `:=` type-declarations should always be a symbol, and I need the name of that for type-checking. Well, I don't need to type check and it slows down the code a bit, but right now I have that feature.

I'm pretty much ready to put the new code on CRAN (#66), except that I cannot get through the test on Debian for some bizarre reason (#65). I cannot see how any of the code could be platform dependent, considering that it is all pure R code, but the Debian R version is one higher than the other versions I can check using `devtools` and those tested when submitting on CRAN.

**Comment by lionel-** [comment] 2018-12-20 13:18
> Isn't :: an inline function? Then foo::bar is a call, surely? True, :: is not a function you will want to modify (any more than you would want to change if or for), but still...

You would still be able to use `typeof()` and `[[` (or even `rlang::node_car()`) for low-level operations with calls. The idea is that `call_name()` is a high-level function. I'm not sure that `is_call()` can be, though. Maybe it's not worth trying to abstract out `::` calls, we'll see.
